export const tvSources = [
  { group: 'Television y Radio en vivo', name: 'Telechancho Infinity', url: 'https://telechancho.github.io/telechancho-iptv/telechancho-infinity.m3u' },

  { group: 'M3U.CL Espanol', name: 'M3U.CL Argentina', url: 'https://www.m3u.cl/lista/AR.m3u' },
  { group: 'M3U.CL Espanol', name: 'M3U.CL Bolivia', url: 'https://www.m3u.cl/lista/BO.m3u' },
  { group: 'M3U.CL Espanol', name: 'M3U.CL Chile', url: 'https://www.m3u.cl/lista/CL.m3u' },
  { group: 'M3U.CL Espanol', name: 'M3U.CL Colombia', url: 'https://www.m3u.cl/lista/CO.m3u' },
  { group: 'M3U.CL Espanol', name: 'M3U.CL Costa Rica', url: 'https://www.m3u.cl/lista/CR.m3u' },
  { group: 'M3U.CL Espanol', name: 'M3U.CL Ecuador', url: 'https://www.m3u.cl/lista/EC.m3u' },
  { group: 'M3U.CL Espanol', name: 'M3U.CL Espana', url: 'https://www.m3u.cl/lista/ES.m3u' },
  { group: 'M3U.CL Espanol', name: 'M3U.CL Mexico', url: 'https://www.m3u.cl/lista/MX.m3u' },
  { group: 'M3U.CL Espanol', name: 'M3U.CL Paraguay', url: 'https://www.m3u.cl/lista/PY.m3u' },
  { group: 'M3U.CL Espanol', name: 'M3U.CL Peru', url: 'https://www.m3u.cl/lista/PE.m3u' },
  { group: 'M3U.CL Espanol', name: 'M3U.CL Republica Dominicana', url: 'https://www.m3u.cl/lista/DO.m3u' },
  { group: 'M3U.CL Espanol', name: 'M3U.CL Venezuela', url: 'https://www.m3u.cl/lista/VE.m3u' },
  { group: 'M3U.CL Espanol', name: 'M3U.CL Musica', url: 'https://www.m3u.cl/lista/musica.m3u' },
  { group: 'M3U.CL Espanol', name: 'M3U.CL Religiosos', url: 'https://www.m3u.cl/lista/religiosos.m3u' },

  { group: 'IPTV-ORG Espanol', name: 'IPTV-ORG Espanol', url: 'https://iptv-org.github.io/iptv/languages/spa.m3u' },
  { group: 'IPTV-ORG Espanol', name: 'IPTV-ORG America Hispanica', url: 'https://iptv-org.github.io/iptv/regions/hispam.m3u' },
  { group: 'IPTV-ORG Espanol', name: 'IPTV-ORG Argentina', url: 'https://iptv-org.github.io/iptv/countries/ar.m3u' },
  { group: 'IPTV-ORG Espanol', name: 'IPTV-ORG Bolivia', url: 'https://iptv-org.github.io/iptv/countries/bo.m3u' },
  { group: 'IPTV-ORG Espanol', name: 'IPTV-ORG Chile', url: 'https://iptv-org.github.io/iptv/countries/cl.m3u' },
  { group: 'IPTV-ORG Espanol', name: 'IPTV-ORG Colombia', url: 'https://iptv-org.github.io/iptv/countries/co.m3u' },
  { group: 'IPTV-ORG Espanol', name: 'IPTV-ORG Costa Rica', url: 'https://iptv-org.github.io/iptv/countries/cr.m3u' },
  { group: 'IPTV-ORG Espanol', name: 'IPTV-ORG Cuba', url: 'https://iptv-org.github.io/iptv/countries/cu.m3u' },
  { group: 'IPTV-ORG Espanol', name: 'IPTV-ORG Ecuador', url: 'https://iptv-org.github.io/iptv/countries/ec.m3u' },
  { group: 'IPTV-ORG Espanol', name: 'IPTV-ORG El Salvador', url: 'https://iptv-org.github.io/iptv/countries/sv.m3u' },
  { group: 'IPTV-ORG Espanol', name: 'IPTV-ORG Espana', url: 'https://iptv-org.github.io/iptv/countries/es.m3u' },
  { group: 'IPTV-ORG Espanol', name: 'IPTV-ORG Guatemala', url: 'https://iptv-org.github.io/iptv/countries/gt.m3u' },
  { group: 'IPTV-ORG Espanol', name: 'IPTV-ORG Honduras', url: 'https://iptv-org.github.io/iptv/countries/hn.m3u' },
  { group: 'IPTV-ORG Espanol', name: 'IPTV-ORG Mexico', url: 'https://iptv-org.github.io/iptv/countries/mx.m3u' },
  { group: 'IPTV-ORG Espanol', name: 'IPTV-ORG Nicaragua', url: 'https://iptv-org.github.io/iptv/countries/ni.m3u' },
  { group: 'IPTV-ORG Espanol', name: 'IPTV-ORG Panama', url: 'https://iptv-org.github.io/iptv/countries/pa.m3u' },
  { group: 'IPTV-ORG Espanol', name: 'IPTV-ORG Paraguay', url: 'https://iptv-org.github.io/iptv/countries/py.m3u' },
  { group: 'IPTV-ORG Espanol', name: 'IPTV-ORG Peru', url: 'https://iptv-org.github.io/iptv/countries/pe.m3u' },
  { group: 'IPTV-ORG Espanol', name: 'IPTV-ORG Puerto Rico', url: 'https://iptv-org.github.io/iptv/countries/pr.m3u' },
  { group: 'IPTV-ORG Espanol', name: 'IPTV-ORG Republica Dominicana', url: 'https://iptv-org.github.io/iptv/countries/do.m3u' },
  { group: 'IPTV-ORG Espanol', name: 'IPTV-ORG Uruguay', url: 'https://iptv-org.github.io/iptv/countries/uy.m3u' },
  { group: 'IPTV-ORG Espanol', name: 'IPTV-ORG Venezuela', url: 'https://iptv-org.github.io/iptv/countries/ve.m3u' },

  { group: 'TDTChannels Espanol', name: 'TDTChannels TV', url: 'https://www.tdtchannels.com/lists/tv.m3u8' },
  { group: 'TDTChannels Espanol', name: 'TDTChannels Radio', url: 'https://www.tdtchannels.com/lists/radio.m3u8' },
  { group: 'TDTChannels Espanol', name: 'TDTChannels TV+Radio', url: 'https://www.tdtchannels.com/lists/tvradio.m3u8' },

  { group: 'Peliculas y series On Demand Latino', name: 'Dibujos animados', url: 'https://mametchikitty.github.io/Listas-IPTV/dibujos-animados.m3u' },
];
